const adverbs = [
  "sweetly",
  "swiftly",
  "hella",
  "remarkably",
  "jauntily",
  "swimmingly",
  "very",
  "extra",
  "perfectly",
  "never",
  "subtly",
  "always",
  "inadvertently",
  "harmoniously",
  "immensely",
  "barely",
  "consistently",
  "mysteriously",
  "strangely",
  "oddly",
  "fondly",
  "meticulously",
  "disappointingly",
  "clearly",
  "slightly",
];
const adjectives = [
  "spicy",
  "swerving",
  "lumpy",
  "snuffly",
  "sweet",
  "suave",
  "sultry",
  "exotic",
  "haunted",
  "musty",
  "emulsified",
  "crispy",
  "toxic",
  "catastrophic",
  "satisfying",
  "squirmy",
  "lucid",
  "delicious",
  "permanent",
  "naked",
  "handsome",
  "charming",
  "arrogant",
  "sly",
  "ugly",
  "muffled",
  "plastic",
  "tricky",
  "nimble",
  "swirly",
  "rich",
  "dingy",
];
const nouns = [
  "antler",
  "weasel",
  "budgie",
  "werewolf",
  "ocelot",
  "pangolin",
  "elephant",
  "quail",
  "charizard",
  "wombat",
  "tooth",
  "ear",
  "kernel",
  "spigot",
  "weevil",
  "osprey",
  "jackal",
  "pencil",
  "telescope",
  "horocrux",
  "muggle",
  "meowth",
  "meow",
  "poptart",
  "igloo",
  "corpse",
  "potato",
  "carnivore",
  "vegan",
  "ukelele",
  "sponge",
  "corgie",
  "sock",
  "boxer",
  "ninja",
  "moon",
  "fridge",
  "doorbell",
  "noodle",
  "hammer",
  "pigeon",
  "squirrel",
  "frog",
  "lamprey",
  "squid",
  "boar",
  "facemask",
  "leopard",
  "toxin",
  "vixen",
  "snail",
  "oligarch",
  "viper",
  "lampshade",
  "cavern",
  "brewpub",
  "hotel",
  "earring",
  "tattoo",
  "cellphone",
  "brick",
  "celery",
  "quinoa",
  "margarita",
  "strain",
  "vehicle",
  "excuse",
  "whisker",
  "prank",
  "window",
  "pillow",
  "claw",
  "tale",
  "milk",
  "finger",
  "stone",
  "curse",
  "pinch",
  "mule",
  "flamethrower",
  "sibling",
  "salmon",
  "freckle",
  "pretzel",
  "banana",
  "papaya",
  "albatross",
  "bowl",
  "day",
  "intention",
  "sunset",
  "sunrise",
  "dusk",
  "dawn",
  "star",
  "owl",
  "hyena",
  "stump",
  "wizard",
  "user",
  "coder",
];

export const generateSillyString = () => {
  const adverb = adverbs[randRange(0, adverbs.length - 1)];
  const adjective = adjectives[randRange(0, adjectives.length - 1)];
  const noun = nouns[randRange(0, nouns.length - 1)];

  return `${adverb}-${adjective}-${noun}`;
};

export const generateMiniSilly = () => {
  const adjective = adjectives[randRange(0, adjectives.length - 1)];
  const noun = nouns[randRange(0, nouns.length - 1)];
  const number = randRange(0, 9999);

  return `${adjective}-${noun}-${number}`;
};

function randRange(minNum, maxNum) {
  return Math.floor(Math.random() * (maxNum - minNum + 1)) + minNum;
}
